const CommentsTypes = {
  ADD_COMMENT: 'ADD_COMMENT',
  ADD_AUTHOR: 'ADD_AUTHOR',
  FETCH_COMMENTS_START: 'FETCH_COMMENTS_START',
  FETCH_COMMENTS_FAILURE: 'FETCH_COMMENTS_FAILURE',
  FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
  COMMENTS_COUNT_INCREMENT: 'COMMENTS_COUNT_INCREMENT',
  COMMENTS_COUNT_DECREMENT: 'COMMENTS_COUNT_DECREMENT',
  COMMENTS_COUNT: 'COMMENTS_COUNT',
};

export default CommentsTypes;
